### PR TITLE
Add option to ignore deprecated resources and data-sources

### PR DESCRIPTION
**Pull request by remilapeyre**

### CODE REVIEW

**Comment by jacobbednarz** [comment]
i've got no weighing on review of this so take it with a grain of salt however, this seems like an antipattern to be using. if a resource is being deprecated, i would expect the documentation to stick around until it is removed in which case, you can then delete the resource and the documentation goes with it; no need for a new flag.

to help the maintainers, could you elaborate a little on your use case?

**Comment by jacobbednarz** [comment]
gotcha, so it's actually the reverse of what i thought 😅 undocumented resources that you don't want to see in the generated output as opposed to removing them.

**Comment by detro** [comment]
A recent bug-fix PR by @jacobbednarz has gone in, so adding en entry to the CHANGELOG should be a bit easier.

Staying tuned as I'd be keen to release this and the other PR.

**Comment by remilapeyre** [comment]
Hi, I will update this tonight.

**Comment by remilapeyre** [comment]
Hi @detro, I'm not sure what is expected for `renderMissingProviderDoc()`, neither resources nor data-sources appear there.

**Review by detro — APPROVED** [review]
🚀

**Comment by detro** [comment]
@remilapeyre @jacobbednarz I'll now be working on releasing this.

I'm thinking I should add a print out of a `--help` command to document what command line option this tool offers now: it's quite substantial.

**Comment by detro** [comment]
And thank you so much to both

**Pull request merged**
